### ISSUE TITLE
changelogファイルからreleasesに移行したgemに対応する

### ISSUE THREAD

**Issue by vividmuimui** [vividmuimui/lock_diff#17]
- mysql
  - https://github.com/brianmario/mysql2/blob/0.4.8/CHANGELOG.md
  - https://github.com/brianmario/mysql2/releases
- i18n
  - https://github.com/svenfuchs/i18n/blob/v0.8.6/CHANGELOG.md
  - https://github.com/svenfuchs/i18n/releases

releaseにはビルドしたものだけおいて、更新履歴はchangelogみたいなケースもあり得る気がするので、
両方出すぐらいがイイのかもしれない
もしくは、最終更新の日時を比較して新しい方を出す

**Comment by skuroki** [comment]
言おうと思ったら既にあった :+1:
https://github.com/lostisland/faraday/blob/v0.12.2/CHANGELOG.md
「もうここに書かないから新しいのはreleases見てね」パターンをちょいちょい見かけますね

**Comment by vividmuimui** [comment]
> 両方出すぐらいがイイのかもしれない�
> もしくは、最終更新の日時を比較して新しい方を出す

をやりつつ、
* 「もうここに書かないから新しいのはreleases見てね」がCHANGELOGに書かれてなければそれをCHANGELOGに追加するPRを出す

を見つけ次第随時やっていくのが良いのかな

**Comment by rastamhadi** [comment]
> 両方出すぐらいがイイのかもしれない

賛成です。
[graphql](https://github.com/rmosolgo/graphql-ruby) みたいに CHANGELOG が複数あるパターンにも対応できますね。
